# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FarizaUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fariza(object):
    def setupUi(self, Fariza):
        Fariza.setObjectName("Fariza")
        Fariza.resize(666, 439)
        font = QtGui.QFont()
        font.setPointSize(8)
        Fariza.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Fariza)
        self.centralwidget.setObjectName("centralwidget")
        self.Title_label = QtWidgets.QLabel(self.centralwidget)
        self.Title_label.setGeometry(QtCore.QRect(190, 20, 281, 91))
        self.Title_label.setMinimumSize(QtCore.QSize(281, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Title_label.setFont(font)
        self.Title_label.setTextFormat(QtCore.Qt.AutoText)
        self.Title_label.setObjectName("Title_label")
        self.Run_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Run_Button.setGeometry(QtCore.QRect(220, 130, 211, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.Run_Button.setFont(font)
        self.Run_Button.setObjectName("Run_Button")
        self.Exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_button.setGeometry(QtCore.QRect(220, 220, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Exit_button.setFont(font)
        self.Exit_button.setObjectName("Exit_button")
        self.conclusion_label = QtWidgets.QLabel(self.centralwidget)
        self.conclusion_label.setGeometry(QtCore.QRect(240, 360, 171, 41))
        self.conclusion_label.setObjectName("conclusion_label")
        self.conclusion_label2 = QtWidgets.QLabel(self.centralwidget)
        self.conclusion_label2.setGeometry(QtCore.QRect(240, 390, 161, 21))
        self.conclusion_label2.setObjectName("conclusion_label2")
        Fariza.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fariza)
        QtCore.QMetaObject.connectSlotsByName(Fariza)

    def retranslateUi(self, Fariza):
        _translate = QtCore.QCoreApplication.translate
        Fariza.setWindowTitle(_translate("Fariza", "MainWindow"))
        self.Title_label.setText(_translate("Fariza", "Welcome to Fariza"))
        self.Run_Button.setText(_translate("Fariza", "Run"))
        self.Exit_button.setText(_translate("Fariza", "Exit"))
        self.conclusion_label.setText(_translate("Fariza", "Fariza 2021@ All Rights Reserved"))
        self.conclusion_label2.setText(_translate("Fariza", "Developed by : Musa Tur Farazi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fariza = QtWidgets.QMainWindow()
    ui = Ui_Fariza()
    ui.setupUi(Fariza)
    Fariza.show()
    sys.exit(app.exec_())
